### ISSUE TITLE
"c --help" doesn't work

### ISSUE THREAD

**Issue by indeyets** [bobuk/c#2]
There is help for sub-commands

```
$ cmd+c --help
Help: {ctrl+c} mark files and directories for copying or moving
```

But there is no help for master command

```
$ c --help
name 'help_cmd' is not defined
```

**Comment by bobuk** [comment]
Yep. Currently here only `cmd+h` or `c h`.
But you are right, I need to add c --help for consistency.

**Comment by bobuk** [comment]
Now it's ok
